openapi: 3.0.0
info:
  title: Pinata Farcaster API
  version: 1.0.0
servers:
  - url: http://{{base_url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /casts/{hash}:
    get:
      tags:
        - default
      summary: Cast by Hash
      parameters:
        - name: hash
          in: path
          schema:
            type: string
          required: true
          description: The full hash of the cast you want to fetch
          example: '0xd3821c9019b42b40b5c173679093e7c19196e379'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:45:57 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '1190'
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Request-Id:
              schema:
                type: string
                example: 71fd2728094f11bd4fce115cc2e5c34c
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  fid: 324525
                  hash: '0xd3821c9019b42b40b5c173679093e7c19196e379'
                  short_hash: '0xd3821c90'
                  thread_hash: null
                  parent_hash: null
                  parent_url: null
                  root_parent_url: https://farcaster.group/spanish
                  parent_author: null
                  author:
                    uid: 324523
                    fid: 324525
                    custody_address: '0x29b9603827ed446bd4e1d2dada0e5aa97e7a455b'
                    recovery_address: '0x00000000fcb080a4d6c39a9354da9eb9bc104cd7'
                    following_count: 116
                    follower_count: 349
                    verifications:
                      - '0xa5d7897e2779f7e5c5be699d41a7b42f9ce0a5c2'
                    bio: |-
                      CryptoUsuario del Web3 y entusiasta DeFi.

                      https://villawolf.eth.limo
                    display_name: Villawolf ðŸŽ©
                    pfp_url: https://i.imgur.com/bX5CFaN.jpg
                    username: villawolf.eth
                  content: >-
                    Si eres Ethereum love ðŸ˜ como yo, esta web no debe faltar en
                    tu cajita de herramientas  https://ultrasound.money ETH ðŸš€ðŸš€
                  timestamp: '2024-02-22T13:35:33Z'
                  embeds:
                    - url: https://i.imgur.com/6CBzQaJ.png
                    - url: https://ultrasound.money
                  reactions:
                    likes:
                      - fid: 7415
                        fname: franklynr
                      - fid: 329015
                        fname: manry
                      - fid: 10981
                        fname: xxtarhxx
                    recasts:
                      - fid: 7415
                        fname: franklynr
                      - fid: 329015
                        fname: manry
                  replies:
                    count: 1
                  mentioned_profiles: []
  /casts:
    get:
      tags:
        - default
      summary: Casts
      parameters:
        - name: fid
          in: query
          schema:
            type: integer
          description: Returns casts from a specific FID
          example: '4823'
        - name: following
          in: query
          schema:
            type: boolean
          description: >-
            When used in combination of `fid` will return the casts for who that
            `fid` is following 
          example: 'true'
        - name: channel
          in: query
          schema:
            type: string
          description: Specify a channel to fetch casts from
          example: https://warpcast.com/~/channel/pinata
        - name: parentHash
          in: query
          schema:
            type: string
          description: Returns casts for a specific parent hash
          example: '0x0ab851ba8524eedf9e164b55f6eeec751f74b539'
        - name: pageSize
          in: query
          schema:
            type: integer
          description: Determine the number of results, if not specified default is 100
          example: '1'
        - name: pageToken
          in: query
          schema:
            type: string
          description: Token to be used for the next page of results
          example: eyJvZmZzZXQiOiIwIn0
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Sat, 09 Mar 2024 20:10:12 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '1696'
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Request-Id:
              schema:
                type: string
                example: 7e395721013189607fb6d458e522efbd
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  casts:
                    - fid: 4823
                      hash: '0x9733fce86e174d1b2d8ba614c7cc0e2ba5372a97'
                      short_hash: '0x9733fce8'
                      thread_hash: '0x317904d560a9acf1d25888322dd8c49afd78eb1f'
                      parent_hash: '0x0ab851ba8524eedf9e164b55f6eeec751f74b539'
                      parent_url: null
                      root_parent_url: https://warpcast.com/~/channel/frames
                      parent_author:
                        uid: 680
                        fid: 680
                        custody_address: '0x0b28a373fc8d92669aefb420499e74ce2dd5d356'
                        recovery_address: '0x00000000fcb080a4d6c39a9354da9eb9bc104cd7'
                        following_count: 777
                        follower_count: 62160
                        verifications:
                          - '0x1aa3096e2bbacae10c316e7282947f635d461e3c'
                          - '0xf417ace7b13c0ef4fcb5548390a450a4b75d3eb3'
                        bio: '@supercast'
                        display_name: â€‹woj â€” q/dau
                        pfp_url: >-
                          https://peach-changing-limpet-80.mypinata.cloud/ipfs/QmZenqRfBERmodRVUHhLaYvYVsRasihVcMY2gqUP2tX7t2?filename=profile_picture.png
                        username: woj.eth
                      author:
                        uid: 4823
                        fid: 4823
                        custody_address: '0x7f9a6992a54dc2f23f1105921715bd61811e5b71'
                        recovery_address: '0x00000000fcb080a4d6c39a9354da9eb9bc104cd7'
                        following_count: 844
                        follower_count: 13623
                        verifications:
                          - '0x1612c6dff0eb5811108b709a30d8150495ce9cc5'
                          - '0xcdcdc174901b12e87cc82471a2a2bd6181c89392'
                        bio: >-
                          Writer. Building @pinatacloud. Tinkering with a
                          Farcaster native alternative to GoodReads:
                          https://readcast.xyz \ https://polluterofminds.com
                        display_name: Justin Hunter
                        pfp_url: >-
                          https://i.seadn.io/gae/lhGgt7yK1JiBVYz_HBxcAmYLRtP03aw5xKX4FgmFT9Ai7kLD5egzlLvb0lkuRNl28shtjr07DC8IHzLUkTqlWUMndUzC9R5_MSxH3g?w=500&auto=format
                        username: polluterofminds
                      content: Noooooooooo
                      timestamp: '2024-03-08T21:12:34Z'
                      embeds: []
                      reactions: {}
                      replies:
                        count: 1
                      mentioned_profiles: []
                  next_page_token: eyJvZmZzZXQiOiIwIn0
  /channels:
    get:
      tags:
        - default
      summary: Channels List
      parameters:
        - name: pageSize
          in: query
          schema:
            type: integer
          description: Determine the number of results, if not specified default is 100
          example: '1'
        - name: pageToken
          in: query
          schema:
            type: string
          description: Token to be used for the next page of results
          example: eyJvZmZzZXQiOiIxMyJ9
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Sat, 09 Mar 2024 20:11:20 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '296'
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Request-Id:
              schema:
                type: string
                example: f7dbd4cc572c4c5fe673a7be66311f65
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  channels:
                    - name: zorablob
                      url: https://warpcast.com/~/channel/zorablob
                      display_name: $ZORB
                      description: Community channel for $ZORB on Zora
                      image_url: https://i.imgur.com/GlH8TPF.png
                      lead_fid: 378922
                      created_at: 1709635092
                  next_page_token: eyJvZmZzZXQiOiIxNCJ9
  /channels/{name}:
    get:
      tags:
        - default
      summary: Channel By Name
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: Display name for the channel you are trying to fetch
          example: pinata
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 06 Mar 2024 18:56:33 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '252'
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Request-Id:
              schema:
                type: string
                example: a752e5f91d68dee584286e893eea6398
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  name: pinata
                  url: https://warpcast.com/~/channel/pinata
                  display_name: pinata
                  description: Build on IPFS and Farcaster at Scale | pinata.cloud
                  image_url: https://i.imgur.com/u4mGk5b.gif
                  lead_fid: 20591
                  created_at: 1706890562
  /users/{fid}:
    get:
      tags:
        - default
      summary: User By FID
      parameters:
        - name: fid
          in: path
          schema:
            type: integer
          required: true
          description: FID for the user you are trying to fetch
          example: '4823'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 06 Mar 2024 18:47:00 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '674'
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Request-Id:
              schema:
                type: string
                example: 6529728aebb6ebf8b575c502cc4c4a4e
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  fid: 4823
                  custody_address: '0x7f9a6992a54dc2f23f1105921715bd61811e5b71'
                  recovery_address: '0x00000000fcb080a4d6c39a9354da9eb9bc104cd7'
                  following_count: 811
                  follower_count: 11049
                  verifications:
                    - '0x1612c6dff0eb5811108b709a30d8150495ce9cc5'
                    - '0xcdcdc174901b12e87cc82471a2a2bd6181c89392'
                  bio: >-
                    Writer. Building @pinatacloud. Tinkering with a Farcaster
                    native alternative to GoodReads: https://readcast.xyz \
                    https://polluterofminds.com
                  display_name: Justin Hunter
                  pfp_url: >-
                    https://i.seadn.io/gae/lhGgt7yK1JiBVYz_HBxcAmYLRtP03aw5xKX4FgmFT9Ai7kLD5egzlLvb0lkuRNl28shtjr07DC8IHzLUkTqlWUMndUzC9R5_MSxH3g?w=500&auto=format
                  username: polluterofminds
  /users:
    get:
      tags:
        - default
      summary: Users
      parameters:
        - name: fid
          in: query
          schema:
            type: integer
          description: Used in combination with `followers` and `following`
          example: '4823'
        - name: followers
          in: query
          schema:
            type: boolean
          description: >-
            When used with `fid` will return the followers of the specified
            `fid`
          example: 'true'
        - name: following
          in: query
          schema:
            type: boolean
          description: When used with `fid` will return the users `fid` is following
          example: 'true'
        - name: pageSize
          in: query
          schema:
            type: integer
          description: Determine the number of results, if not specified default is 100
          example: '1'
        - name: pageToken
          in: query
          schema:
            type: string
          description: Token to be used for the next page of results
          example: eyJvZmZzZXQiOiIyMyJ9
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Sat, 09 Mar 2024 20:12:29 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '826'
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Request-Id:
              schema:
                type: string
                example: cd963fc058d81cdd4c367b44f8e9da52
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15724800; includeSubDomains
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  users:
                    - fid: 2
                      custody_address: '0x4114e33eb831858649ea3702e1c9a2db3f626446'
                      recovery_address: '0x00000000fcb080a4d6c39a9354da9eb9bc104cd7'
                      following_count: 1138
                      follower_count: 150650
                      verifications:
                        - '0x182327170fc284caaa5b1bc3e3878233f529d741'
                        - >-
                          0x83f7335253bfaf321de49f25f6fd67fa8f1d0665b4cab33f67f7e4341bfd91d0
                        - '0x91031dcfdea024b4d51e775486111d2b2a715871'
                        - >-
                          0x91701714719f1388e7f5cf8156b7bcdf001e5dcd1354151488959fdf343caff5
                        - '0xf86a7a5b7c703b1fd8d93c500ac4cc75b67477f0'
                      bio: |-
                        Technowatermelon. Elder Millenial. Building Farcaster. 

                        nf.td/varun
                      display_name: Varun Srinivasan
                      pfp_url: >-
                        https://i.seadn.io/gae/sYAr036bd0bRpj7OX6B-F-MqLGznVkK3--DSneL_BT5GX4NZJ3Zu91PgjpD9-xuVJtHq0qirJfPZeMKrahz8Us2Tj_X8qdNPYC-imqs?w=500&auto=format
                      username: v
                  next_page_token: eyJvZmZzZXQiOiIyIn0
